### ISSUE TITLE
unknown bucket for datetime

### ISSUE THREAD

**Issue by mshanm10** [metamx/druid-spark-batch#62] opened 2016-04-11 21:11 UTC
I am having trouble indexing using druid-spark-batch, getting the following error. Have anybody encountered this error.

```
(TID 2, 192.168.0.11): com.metamx.common.ISE: unknown bucket for datetime 1375329600000. Known values are Set(1376784000000, 1376092800000, 1377216000000, 1376697600000, 1376352000000, 1377388800000, 1375833600000, 1375747200000, 1375315200000, 1375660800000, 1377820800000, 1377734400000, 1375488000000, 1376265600000, 1376611200000, 1377129600000, 1375401600000, 1376870400000, 1377043200000, 1377561600000, 1376524800000, 1376179200000, 1377302400000, 1377475200000, 1377648000000, 1375574400000, 1375920000000, 1376438400000, 1376006400000, 1376956800000, 1377907200000)
	at io.druid.indexer.spark.DateBucketPartitioner.getPartition(SparkDruidIndexer.scala:625)
	at org.apache.spark.util.collection.ExternalSorter.getPartition(ExternalSorter.scala:104)
	at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:212)
	at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:73)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by drcrallen** [comment] 2016-04-13 20:14
All the bucket timestamps are at date intervals in UTC, but your "unknown" time of 1375329600000 is at GMT+4 compared to an even date time. Do you have your timezone settings correct everywhere?

**Comment by drcrallen** [comment] 2016-04-13 20:16
The task attempts to set properties of `"user.timezone", "UTC"` and `"file.encoding", "UTF-8"` but might not do it at the right point in the process. Setting the JVM options to force user.timezone to UTC and file.encoding to UTF-8 are strongly encouraged

**Comment by mshanm10** [comment] 2016-04-21 22:18
Thanks, that gave me the clue. I was using spark 1.5.2 and this issue was caused by https://issues.apache.org/jira/browse/SPARK-10162. I have changed the machine timezone to UTC for short term workaround.

**Comment by drcrallen** [comment] 2016-04-23 16:55
Cool, closing. Please mention here if the issue is not resolved.

**Closed by drcrallen** 2016-04-23 16:55 UTC

**Comment by zlosim** [comment] 2017-03-10 16:51
Hi
I'm getting the same error except I'm using spark 1.6.1
I'm running middle manager with  -Duser.timezone=UTC
and in index task log I can see
`
2017-03-10T16:34:03,465 INFO [main] io.druid.cli.CliPeon - * druid.indexer.runner.javaOpts: -server -Xmx3072m -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -Duser.timezone=UTC -Dfile.encoding=UTF-8 -Dja
va.util.logging.manager=org.apache.logging.log4j.jul.LogManager -Djava.security.auth.login.config=/opt/mapr/conf/mapr.login.conf
2017-03-10T16:34:03,471 INFO [main] io.druid.cli.CliPeon - * user.timezone: UTC`
ale in spark properties i can see user.timezone set to UTC

Is there any other way to fix or I`m just stuck with changing machines default timezone to UTC?

```
> 
> Caused by: com.metamx.common.ISE: unknown bucket for datetime 1483225200000. Known values are Set(1454716800000, 1500163200000, 1491004800000, 1476835200000, 1477267200000, 1464134400000, 1498003200000, 1487894400000, 1501718400000, 1495
> 152000000, 1462492800000, 1474761600000, 1491523200000, 1482796800000, 1457740800000, 1467072000000, 1458345600000, 1461888000000, 1501286400000, 1496620800000, 1481241600000, 1457654400000, 1483747200000, 1500595200000, 1492041600000, 1
> 464825600000, 1482969600000, 1479168000000, 1458691200000, 1477612800000, 1455148800000, 1493942400000, 1475452800000, 1501459200000, 1461283200000, 1477180800000, 1460246400000, 1472774400000, 1468195200000, 1491782400000, 1485043200000
> , 1500681600000, 1464739200000, 1483660800000, 1480809600000, 1453939200000, 1457049600000, 1486512000000, 1469491200000, 1455494400000, 1492905600000, 1476921600000, 1470873600000, 1475798400000, 1482710400000, 1494633600000, 1497139200
> 000, 1467849600000, 1457395200000, 1463011200000, 1462752000000, 1455753600000, 1473292800000, 1487980800000, 1481932800000, 1462147200000, 1468022400000, 1498694400000, 1485388800000, 1496534400000, 1467590400000, 1479081600000, 1459296
> 000000, 1487289600000, 1500940800000, 1485561600000, 1476662400000, 1455580800000, 1454976000000, 1471046400000, 1488585600000, 1458777600000, 1491609600000, 1478390400000, 1462579200000, 1454457600000, 1454544000000, 1460332800000, 1468
> 972800000, 1458000000000, 1492214400000, 1479427200000, 1452470400000, 1473033600000, 1480636800000, 1478131200000, 1461715200000, 1490313600000, 1453248000000, 1473120000000, 1473724800000, 1465084800000, 1477872000000, 1461196800000, 1
> 486857600000, 1453680000000, 1488067200000, 1468886400000, 1487462400000, 1500076800000, 1488499200000, 1469232000000, 1484870400000, 1482105600000, 1484265600000, 1475712000000, 1462060800000, 1496793600000, 1486944000000, 1472169600000
> , 1468368000000, 1458432000000, 1495238400000, 1500768000000, 1458172800000, 1476230400000, 1474502400000, 1498089600000, 1466467200000, 1474848000000, 1492819200000, 1484697600000, 1491264000000, 1490918400000, 1463097600000, 1486252800
> 000, 1493424000000, 1487203200000, 1476576000000, 1495929600000, 1490140800000, 1490486400000, 1493251200000, 1478476800000, 1454112000000, 1497571200000, 1498953600000, 1470182400000, 1497830400000, 1453852800000, 1463961600000, 1454889
> 600000, 1476144000000, 1467331200000, 1470787200000, 1492473600000, 1494806400000, 1497657600000, 1461456000000, 1463875200000, 1491436800000, 1469145600000, 1474070400000, 1488672000000, 1495584000000, 1499817600000, 1496966400000, 1478
> 563200000, 1473638400000, 1500422400000, 1475884800000, 1479513600000, 1470528000000, 1482537600000, 1470268800000, 1494892800000, 14
```

**Comment by drcrallen** [comment] 2017-03-10 17:09
The JVM time zone is expected to be UTC, I honestly don't have a good way to check how non-UTC system timezones impact the system.

I would *THINK* if the hardware clock is set to UTC and the systems is using whatever timezone, that the JVM would be able to correctly use UTC for its own stuff. But again, I don't have a test bed to look at such scenarios.
